application: fullmovie4me 
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /vendor
  static_dir: vendor

- url: /.*
  script: fullmovie4me.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
